<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Ft8Client.Integrations</RootNamespace>

  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ft8Client.Core\Ft8Client.Core.csproj" />
    <ProjectReference Include="..\Ft8Client.Data\Ft8Client.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Ft8Client.Integrations.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
  </ItemGroup>
</Project>
